### ISSUE TITLE
Support AWS Provider v4, Support latest `context.tf`

### ISSUE THREAD

**Issue by korenyoni** [cloudposse/terraform-aws-s3-website#75]
Have a question? Please checkout our [Slack Community](https://slack.cloudposse.com) or visit our [Slack Archive](https://archive.sweetops.com/). 

[![Slack Community](https://slack.cloudposse.com/badge.svg)](https://slack.cloudposse.com)

## Describe the Feature

* `cloudposse/s3-log-storage/aws` depends on `cloudposse/s3-bucket/aws`, which requires v4 of the AWS Provider
* `context.tf` is still using `null-label` `0.24.1.` instead of `0.25.0`

## Expected Behavior

This module should use the latest version of the aforementioned dependencies

## Use Case

* Latest dependencies should be used
* `tenant` label cannot be used because `null-label` `0.25.0` is not used

## Describe Ideal Solution

Support latest AWS Provider and manually update `context.tf`

## Alternatives Considered

N/A

## Additional Context

N/A

**Comment by michaelmoreira** [comment]
It sounds like you are suggesting updating the cloudposse/s3-log-storage/aws module to use the latest version of the AWS Provider and other dependencies. Currently, this module depends on cloudposse/s3-bucket/aws, which requires version 4 of the AWS Provider, but the context.tf file in the cloudposse/s3-log-storage/aws module is still using version 0.24.1 of the null-label provider.

To fix this issue, you can update the context.tf file in the cloudposse/s3-log-storage/aws module to use the latest version of the null-label provider (0.25.0 or higher). This will ensure that the cloudposse/s3-log-storage/aws module is compatible with the dependencies it uses, including cloudposse/s3-bucket/aws, which requires version 4 of the AWS Provider.

Additionally, you can update the cloudposse/s3-log-storage/aws module to use the latest versions of any other dependencies it may have, in order to take advantage of the latest features and improvements.

Overall, updating the cloudposse/s3-log-storage/aws module to use the latest versions of its dependencies will ensure compatibility and allow users to take advantage of the latest features and improvements.
